### ISSUE TITLE
Maps showing incomplete Asserted Distributions

### ISSUE THREAD

**Issue by lvhart2** [sfg-taxonpages/plecoptera#4]
When I search for a species, ex: Nemoura arctica, on PSF, the map gives an incomplete asserted distribution. Only Ohio is highlighted. This needs fixing-not sure what the source is for the distribution that does show up. 

New PSF:
<img width="1380" alt="Screenshot 2023-09-14 at 3 30 17 PM" src="https://github.com/sfg-taxonpages/plecoptera/assets/75492546/292c7776-daec-4d25-8428-bdc404c80d16">

Old PSF:
<img width="1090" alt="Screenshot 2023-09-14 at 3 33 10 PM" src="https://github.com/sfg-taxonpages/plecoptera/assets/75492546/8fe2c2e4-693e-4729-b746-396e38f8245f">

@redewalt @mjy

**Comment by redewalt** [comment]
We have records for Ohio and Mongolia because there are specimen records for it. But as you can see in the old database there are lots of TDWG geographies in North America, Europe, and Asia Temperate. There are also finer scale text available: Canada: AB, BC, LB, MB, NB, NF, NS, NT, NU, ON, PEI, PQ, SK, YK. USA: AK, IA, IL, ME, MI, MN, NH, NY, OH, PA, SD, WI, WV, WY. Finland, Norway. Mongolia: Arkhangai, Bayan-Olgii, Bayankhongor, Bulgan, Dornod, Govi-Altai, Khovsgol, Khovd, Selenge, Tov, Ulaanbaatar, Uvs, Zavkhan. Russia N. Russia Far E: Kamchatka, Magadan, Khabarovsk, Primorye, Sakhalin Is., Amur, West Siberia. Baltic States. Sweden.

These TDWG assertions apparently have not source. I suggest that a dummy source be created called "Zwick & DeWalt assertions". I am sure this is a common problem in Plecoptera SF because most data were imported from Peter Zwick in 2008 and the rest added by DeWalt but without attribution to a literature.

**Comment by mjy** [comment]
Source is created for these, edited as needed: https://sfg.taxonworks.org/tasks/sources/new_source?source_id=200231.

**Comment by mjy** [comment]
Distribution text (and the 3 other categories) is published now, e.g. https://sfg-taxonpages.github.io/plecoptera/#/otus/895760/overview.

**Comment by mjy** [comment]
Distribution data are updated and live in the preview site.  They should be displaying for all but the 30 shapes we are in the process of updating:

1: Europe (OK)
10: Northern Europe (OK)
10NOR-OO: Norway (OK)
10NOR: Norway (OK)
2: Africa (OK)
22: West Tropical Africa (OK)
22NGA-OO: Nigeria (OK)
22NGA: Nigeria (OK)
3: Asia Temperate (OK)
30: Siberia (OK)
30KRA-OO: Krasnoyarsk (OK)
30KRA: Krasnoyarsk (OK)
31: Russian Far East (OK)
31MAG-OO: Magadan (OK)
31MAG: Magadan (OK)
4: Asia Tropical (OK)
41: Indo-China (OK)
41AND-AN: Andaman Is. (OK)
41AND: Andaman Is. (OK)
6: Pacific (OK)
60: Southwestern Pacific (OK)
61: South-Central Pacific (OK)
61SCI-OO: Society Is. (OK)
61SCI: Society Is. (OK)
7: Northern America (OK)
72: Eastern Canada (OK)
72NFL-NE: Newfoundland (OK)
72NFL: Newfoundland (OK)
73: Northwestern U.S.A. (OK)
9: Antarctic (OK)

**Comment by jrflood** [comment]
All anomalous (?) PSF taxa have had distribution added, with the exception of Leuctra slovenica which I can't find in sfg-TW.
All the above shapes have been verified as well.

**Comment by mjy** [comment]
Should be resolved.  Genus and higher are re-indexing now.
